server:
  port: 8761

spring:
  profiles:
    active: local
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    wait-time-in-ms-when-sync-empty: 0  # ?? ????? ??? ?? ??? ?? ?? ?? ?? ??
    response-cache-update-interval-ms: 30000  # ??????? ??? ??? ?? ??? 30??? ??
