name: unionmate dev CD 파이프라인

on:
  workflow_run:
    workflows: ["discovery-service CI pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read

    steps:
      - name: Docker 이미지 dev 서버 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEV_HOST}}
          username: ${{secrets.DEV_USERNAME}}
          key: ${{secrets.DEV_KEY}}
          script: |
            cd /home/ubuntu
            docker rm -f discovery-service-dev || true
            docker compose pull discovery-service-dev
            docker compose up -d --no-deps --force-recreate --pull always discovery-service-dev
            docker image prune -f
